// packages/vue3-vite/src/components/ui/toggle.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '@/lib/utils';

interface ToggleProps {
  modelValue?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<ToggleProps>(), {
  modelValue: false,
});

const emit = defineEmits<{ 'update:modelValue': [value: boolean] }>();

const className = computed(() =>
  cn(
    'inline-flex h-10 items-center justify-center rounded-md px-3 text-sm font-medium transition-colors',
    props.modelValue
      ? 'bg-gray-200 text-gray-900'
      : 'bg-transparent hover:bg-gray-100',
    props.class
  )
);
</script>

<template>
  <button
    type="button"
    :class="className"
    @click="emit('update:modelValue', !modelValue)"
  >
    <slot />
  </button>
</template>

// packages/react-vite/src/components/ui/toggle.tsx
import * as React from 'react';
import * as TogglePrimitive from '@radix-ui/react-toggle';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '@/lib/utils';

const toggleVariants = cva(
  'inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-white transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 data-[state=on]:bg-gray-100 data-[state=on]:text-gray-900',
  {
    variants: {
      variant: {
        default: 'bg-transparent',
        outline:
          'border border-gray-300 bg-transparent hover:bg-gray-100 hover:text-gray-900',
      },
      size: {
        default: 'h-10 px-3',
        sm: 'h-9 px-2.5',
        lg: 'h-11 px-5',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
);

const Toggle = React.forwardRef<
  React.ElementRef<typeof TogglePrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof TogglePrimitive.Root> &
    VariantProps<typeof toggleVariants>
>(({ className, variant, size, ...props }, ref) => (
  <TogglePrimitive.Root
    ref={ref}
    className={cn(toggleVariants({ variant, size, className }))}
    {...props}
  />
));

Toggle.displayName = TogglePrimitive.Root.displayName;

export { Toggle, toggleVariants };
