// packages/vue3-vite/src/examples/form-example.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useForm } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import { z } from 'zod'
import Button from '@/components/ui/button.vue'
import Input from '@/components/ui/input.vue'
import Select from '@/components/ui/select.vue'
import Checkbox from '@/components/ui/checkbox.vue'
import Label from '@/components/ui/label.vue'

const userFormSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(50, 'Name must be at most 50 characters'),
  email: z.string().email('Enter a valid email address'),
  role: z.enum(['admin', 'user'], { required_error: 'Select a role' }),
  agreeTerms: z.boolean().refine((value) => value === true, 'You must accept the terms'),
})

type UserFormValues = z.infer<typeof userFormSchema>

const roleOptions = [
  { label: 'User', value: 'user' },
  { label: 'Admin', value: 'admin' },
]

const { defineField, errors, handleSubmit, resetForm, isSubmitting } = useForm<UserFormValues>({
  validationSchema: toTypedSchema(userFormSchema),
  initialValues: {
    name: '',
    email: '',
    role: undefined,
    agreeTerms: false,
  },
})

const [name] = defineField('name')
const [email] = defineField('email')
const [role] = defineField('role')
const [agreeTerms] = defineField('agreeTerms')

const submitLabel = computed(() => (isSubmitting.value ? 'Submitting...' : 'Submit'))

const onSubmit = handleSubmit(async (values) => {
  console.log('Form values:', values)
  resetForm()
})
</script>

<template>
  <form class="space-y-6 p-6 rounded-lg border border-gray-200 bg-white" @submit.prevent="onSubmit">
    <div class="space-y-2">
      <Label for="name">Name</Label>
      <Input id="name" v-model="name" placeholder="Your name" />
      <p v-if="errors.name" class="text-sm font-medium text-red-500">{{ errors.name }}</p>
    </div>

    <div class="space-y-2">
      <Label for="email">Email</Label>
      <Input id="email" v-model="email" type="email" placeholder="you@example.com" />
      <p class="text-sm text-gray-500">We will never share your email.</p>
      <p v-if="errors.email" class="text-sm font-medium text-red-500">{{ errors.email }}</p>
    </div>

    <div class="space-y-2">
      <Label for="role">Role</Label>
      <Select id="role" v-model="role" :options="roleOptions" placeholder="Choose a role" />
      <p v-if="errors.role" class="text-sm font-medium text-red-500">{{ errors.role }}</p>
    </div>

    <div class="flex flex-row items-start space-x-3 space-y-0">
      <Checkbox id="agreeTerms" v-model="agreeTerms" class="mt-1" />
      <div class="space-y-1 leading-none">
        <Label for="agreeTerms">I agree to the terms and privacy policy</Label>
        <p v-if="errors.agreeTerms" class="text-sm font-medium text-red-500">{{ errors.agreeTerms }}</p>
      </div>
    </div>

    <Button type="submit" :disabled="isSubmitting">{{ submitLabel }}</Button>
  </form>
</template>

// packages/react-vite/src/examples/form-example.tsx
/**
 * Form reference — React Hook Form + Zod + shadcn-style Form primitives.
 * Agents can copy patterns, not this file wholesale, into production code.
 */

import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
    Form,
    FormControl,
    FormDescription,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';

// ============================================
// 1. Zod schema
// ============================================

const userFormSchema = z.object({
    name: z.string().min(2, 'Name must be at least 2 characters').max(50, 'Name must be at most 50 characters'),
    email: z.string().email('Enter a valid email address'),
    role: z.enum(['admin', 'user'], { required_error: 'Select a role' }),
    agreeTerms: z.boolean().refine(val => val === true, 'You must accept the terms'),
});

type UserFormValues = z.infer<typeof userFormSchema>;

// ============================================
// 2. Form component
// ============================================

interface UserFormProps {
    defaultValues?: Partial<UserFormValues>;
    onSubmit: (data: UserFormValues) => void | Promise<void>;
    loading?: boolean;
}

export function UserFormExample({ defaultValues, onSubmit, loading }: UserFormProps) {
    const form = useForm<UserFormValues>({
        resolver: zodResolver(userFormSchema),
        defaultValues: {
            name: '',
            email: '',
            role: undefined,
            agreeTerms: false,
            ...defaultValues,
        },
    });

    const handleSubmit = async (data: UserFormValues) => {
        try {
            await onSubmit(data);
            form.reset();
        } catch (error) {
            console.error('Form submit failed:', error);
        }
    };

    return (
        <Form {...form}>
            <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-6">
                {/* Text input */}
                <FormField
                    control={form.control}
                    name="name"
                    render={({ field }) => (
                        <FormItem>
                            <FormLabel>Name</FormLabel>
                            <FormControl>
                                <Input placeholder="Your name" {...field} />
                            </FormControl>
                            <FormMessage />
                        </FormItem>
                    )}
                />

                {/* Email */}
                <FormField
                    control={form.control}
                    name="email"
                    render={({ field }) => (
                        <FormItem>
                            <FormLabel>Email</FormLabel>
                            <FormControl>
                                <Input type="email" placeholder="you@example.com" {...field} />
                            </FormControl>
                            <FormDescription>We will never share your email.</FormDescription>
                            <FormMessage />
                        </FormItem>
                    )}
                />

                {/* Select */}
                <FormField
                    control={form.control}
                    name="role"
                    render={({ field }) => (
                        <FormItem>
                            <FormLabel>Role</FormLabel>
                            <Select onValueChange={field.onChange} defaultValue={field.value}>
                                <FormControl>
                                    <SelectTrigger>
                                        <SelectValue placeholder="Choose a role" />
                                    </SelectTrigger>
                                </FormControl>
                                <SelectContent>
                                    <SelectItem value="user">User</SelectItem>
                                    <SelectItem value="admin">Admin</SelectItem>
                                </SelectContent>
                            </Select>
                            <FormMessage />
                        </FormItem>
                    )}
                />

                {/* Checkbox */}
                <FormField
                    control={form.control}
                    name="agreeTerms"
                    render={({ field }) => (
                        <FormItem className="flex flex-row items-start space-x-3 space-y-0">
                            <FormControl>
                                <Checkbox checked={field.value} onCheckedChange={field.onChange} />
                            </FormControl>
                            <div className="space-y-1 leading-none">
                                <FormLabel>I agree to the terms and privacy policy</FormLabel>
                            </div>
                        </FormItem>
                    )}
                />

                <Button type="submit" disabled={loading}>
                    {loading ? 'Submitting…' : 'Submit'}
                </Button>
            </form>
        </Form>
    );
}

export default UserFormExample;
