// packages/react-vite/src/components/ui/radio-group.tsx
import * as React from 'react';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
import { Circle } from 'lucide-react';

import { cn } from '@/lib/utils';

const RadioGroup = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root>
>(({ className, ...props }, ref) => {
  return (
    <RadioGroupPrimitive.Root
      className={cn('grid gap-2', className)}
      {...props}
      ref={ref}
    />
  );
});
RadioGroup.displayName = RadioGroupPrimitive.Root.displayName;

const RadioGroupItem = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Item>
>(({ className, ...props }, ref) => {
  return (
    <RadioGroupPrimitive.Item
      ref={ref}
      className={cn(
        'aspect-square h-4 w-4 rounded-full border border-gray-300 text-blue-600 ring-offset-white focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
        className
      )}
      {...props}
    >
      <RadioGroupPrimitive.Indicator className='flex items-center justify-center'>
        <Circle className='h-2.5 w-2.5 fill-current text-current' />
      </RadioGroupPrimitive.Indicator>
    </RadioGroupPrimitive.Item>
  );
});
RadioGroupItem.displayName = RadioGroupPrimitive.Item.displayName;

export { RadioGroup, RadioGroupItem };

// packages/vue3-vite/src/components/ui/radio-group.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cn } from '@/lib/utils'

export interface RadioOption {
  label: string
  value: string
  disabled?: boolean
}

interface RadioGroupProps {
  modelValue?: string
  options: RadioOption[]
  name: string
  class?: string
}

const props = defineProps<RadioGroupProps>()
const emit = defineEmits<{ 'update:modelValue': [value: string] }>()

const className = computed(() => cn('grid gap-2', props.class))
</script>

<template>
  <div :class="className">
    <label
      v-for="option in options"
      :key="option.value"
      class="flex items-center gap-2 text-sm"
      :class="option.disabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'"
    >
      <input
        type="radio"
        :name="name"
        :value="option.value"
        :checked="modelValue === option.value"
        :disabled="option.disabled"
        class="h-4 w-4 border-gray-300 text-blue-600 focus:ring-blue-500"
        @change="emit('update:modelValue', option.value)"
      />
      <span>{{ option.label }}</span>
    </label>
  </div>
</template>
