// packages/react-vite/src/examples/list-page-example.tsx
/**
 * List page reference — patterns for data tables, search, and pagination.
 * Copy ideas, not this file verbatim, into production code.
 */

import { useState } from 'react';
import { useApi } from '@/lib/services';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';

// ============================================
// 1. Shared types (adjust to your API contract)
// ============================================

/** Paginated list payload */
interface PaginatedResult<T> {
    list: T[];
    total: number;
    page: number;
    pageSize: number;
}

/** Query params for list endpoints */
interface ListParams {
    page: number;
    pageSize: number;
    keyword?: string;
}

// ============================================
// 2. Domain model
// ============================================

interface Product {
    id: string;
    name: string;
    price: number;
    category: string;
    stock: number;
}

// Mock fetch — swap for real `api.get` + `extractApiData`
const mockFetchProducts = async (params: ListParams): Promise<PaginatedResult<Product>> => {
    await new Promise(resolve => setTimeout(resolve, 500));

    return {
        list: [
            { id: '1', name: 'Product A', price: 99.99, category: 'Electronics', stock: 100 },
            { id: '2', name: 'Product B', price: 199.99, category: 'Apparel', stock: 50 },
            { id: '3', name: 'Product C', price: 49.99, category: 'Grocery', stock: 200 },
        ],
        total: 3,
        page: params.page,
        pageSize: params.pageSize,
    };
};

// ============================================
// 3. Example page component
// ============================================

export function ProductListExample() {
    const [params, setParams] = useState<ListParams>({
        page: 1,
        pageSize: 10,
        keyword: '',
    });

    const { data, loading, error, refetch } = useApi(
        () => mockFetchProducts(params),
        [params.page, params.pageSize, params.keyword]
    );

    const handleSearch = (keyword: string) => {
        setParams(prev => ({ ...prev, keyword, page: 1 }));
    };

    const handlePageChange = (page: number) => {
        setParams(prev => ({ ...prev, page }));
    };

    const handleDelete = async (id: string) => {
        if (confirm('Delete this item?')) {
            // await productApi.delete(id);
            console.log('deleted:', id);
            refetch();
        }
    };

    if (error) {
        return (
            <div className="p-4 text-center text-red-500">
                Failed to load: {error.message}
                <Button onClick={refetch} className="ml-2">Retry</Button>
            </div>
        );
    }

    return (
        <div className="p-6 space-y-6">
            <div className="flex justify-between items-center">
                <h1 className="text-2xl font-bold">Products</h1>
                <Button>Add product</Button>
            </div>

            <div className="flex gap-4">
                <Input
                    placeholder="Search products…"
                    value={params.keyword}
                    onChange={e => handleSearch(e.target.value)}
                    className="max-w-sm"
                />
                <Button variant="outline" onClick={refetch}>Refresh</Button>
            </div>

            {loading && (
                <div className="text-center py-8 text-gray-500">Loading…</div>
            )}

            {!loading && data && (
                <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                    {data.list.map(product => (
                        <Card key={product.id} className="p-4">
                            <h3 className="font-semibold text-lg">{product.name}</h3>
                            <p className="text-gray-500 text-sm">{product.category}</p>
                            <div className="flex justify-between items-center mt-4">
                                <span className="text-blue-600 font-bold">¥{product.price}</span>
                                <span className="text-gray-400 text-sm">Stock: {product.stock}</span>
                            </div>
                            <div className="flex gap-2 mt-4">
                                <Button size="sm" variant="outline">Edit</Button>
                                <Button size="sm" variant="destructive" onClick={() => handleDelete(product.id)}>
                                    Delete
                                </Button>
                            </div>
                        </Card>
                    ))}
                </div>
            )}

            {!loading && data?.list.length === 0 && (
                <div className="text-center py-8 text-gray-500">No data</div>
            )}

            {data && data.total > params.pageSize && (
                <div className="flex justify-center gap-2">
                    <Button
                        variant="outline"
                        disabled={params.page <= 1}
                        onClick={() => handlePageChange(params.page - 1)}
                    >
                        Previous
                    </Button>
                    <span className="px-4 py-2">
                        Page {params.page} / {Math.ceil(data.total / params.pageSize)}
                    </span>
                    <Button
                        variant="outline"
                        disabled={params.page >= Math.ceil(data.total / params.pageSize)}
                        onClick={() => handlePageChange(params.page + 1)}
                    >
                        Next
                    </Button>
                </div>
            )}
        </div>
    );
}

export default ProductListExample;

// packages/vue3-vite/src/examples/list-page-example.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import Button from '@/components/ui/button.vue';
import Card from '@/components/ui/card.vue';
import Input from '@/components/ui/input.vue';
import { useApi } from '@/lib/services';

interface Product {
  id: string;
  name: string;
  price: number;
  category: string;
  stock: number;
}

interface PaginatedResult<T> {
  list: T[];
  total: number;
  page: number;
  pageSize: number;
}

const page = ref(1);
const pageSize = ref(10);
const keyword = ref('');

const mockFetchProducts = async (): Promise<PaginatedResult<Product>> => {
  await new Promise(resolve => setTimeout(resolve, 350));

  const source: Product[] = [
    {
      id: '1',
      name: 'Product A',
      price: 99.99,
      category: 'Electronics',
      stock: 100,
    },
    {
      id: '2',
      name: 'Product B',
      price: 199.99,
      category: 'Apparel',
      stock: 50,
    },
    {
      id: '3',
      name: 'Product C',
      price: 49.99,
      category: 'Grocery',
      stock: 200,
    },
  ];

  const filtered = source.filter(item =>
    item.name.toLowerCase().includes(keyword.value.toLowerCase())
  );

  return {
    list: filtered,
    total: filtered.length,
    page: page.value,
    pageSize: pageSize.value,
  };
};

const { data, loading, error, refetch } = useApi(mockFetchProducts, {
  immediate: true,
});

watch([page, pageSize, keyword], () => {
  void refetch();
});

const totalPages = computed(() => {
  if (!data.value || data.value.total === 0) return 1;
  return Math.ceil(data.value.total / pageSize.value);
});

function nextPage(): void {
  if (page.value < totalPages.value) {
    page.value += 1;
  }
}

function prevPage(): void {
  if (page.value > 1) {
    page.value -= 1;
  }
}
</script>

<template>
  <section class="p-6 space-y-6">
    <div class="flex justify-between items-center">
      <h1 class="text-2xl font-bold">Products</h1>
      <Button>Add product</Button>
    </div>

    <div class="flex gap-4">
      <Input
        v-model="keyword"
        placeholder="Search products..."
        class="max-w-sm"
      />
      <Button variant="outline" @click="refetch">Refresh</Button>
    </div>

    <div v-if="error" class="p-4 text-center text-red-500">
      Failed to load: {{ error.message }}
      <Button class="ml-2" @click="refetch">Retry</Button>
    </div>

    <div v-else-if="loading" class="text-center py-8 text-gray-500">
      Loading...
    </div>

    <div
      v-else-if="data && data.list.length > 0"
      class="grid gap-4 md:grid-cols-2 lg:grid-cols-3"
    >
      <Card v-for="product in data.list" :key="product.id" class="p-4">
        <h3 class="font-semibold text-lg">{{ product.name }}</h3>
        <p class="text-gray-500 text-sm">{{ product.category }}</p>
        <div class="flex justify-between items-center mt-4">
          <span class="text-blue-600 font-bold">${{ product.price }}</span>
          <span class="text-gray-400 text-sm">Stock: {{ product.stock }}</span>
        </div>
        <div class="flex gap-2 mt-4">
          <Button size="sm" variant="outline">Edit</Button>
          <Button size="sm" variant="destructive">Delete</Button>
        </div>
      </Card>
    </div>

    <div v-else class="text-center py-8 text-gray-500">No data</div>

    <div v-if="data && data.total > pageSize" class="flex justify-center gap-2">
      <Button variant="outline" :disabled="page <= 1" @click="prevPage"
        >Previous</Button
      >
      <span class="px-4 py-2">Page {{ page }} / {{ totalPages }}</span>
      <Button variant="outline" :disabled="page >= totalPages" @click="nextPage"
        >Next</Button
      >
    </div>
  </section>
</template>
